### ISSUE TITLE
authorize-account => ERROR 500 internal_error Unexpected exception

### ISSUE THREAD

**Issue by julled** [Backblaze/B2_Command_Line_Tool#475] opened 2018-07-29 09:53 UTC
Hey there,
i have created an account and created a application key in the web-interface.
When trying to auth my account via
`b2 authorize-account --debugLogs xxx yyyy`
It says:
`Using https://api.backblazeb2.com
ERROR: unable to authorize account: 500 internal_error Unexpected exception
`

Is there a server-side issue right now? I also tried it 10hours ago, resulting in the same problem.

The logs are as following:
cat b2_cli.log 
2018-07-29 09:42:03,977	15533	140570594121472	b2.console_tool	INFO	// ========================================  1.3.2   ======================================== \\
2018-07-29 09:42:03,978	15533	140570594121472	b2.console_tool	DEBUG	platform is Linux-4.4.0-130-generic-x86_64-with-debian-stretch-sid
2018-07-29 09:42:03,978	15533	140570594121472	b2.console_tool	DEBUG	Python version is CPython 2.7.12 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:42:40)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
2018-07-29 09:42:03,978	15533	140570594121472	b2.console_tool	DEBUG	locale is ('en_US', 'UTF-8')
2018-07-29 09:42:03,978	15533	140570594121472	b2.console_tool	DEBUG	filesystem encoding is UTF-8
2018-07-29 09:42:03,978	15533	140570594121472	b2.console_tool	INFO	starting command [b2.console_tool.AuthorizeAccount] (arguments hidden)
2018-07-29 09:42:03,979	15533	140570594121472	b2.api	DEBUG	calling authorize_account(self=<b2.api.B2Api object at 0x7fd91cb6b0d0>, realm='production') (hidden args: account_id_or_key_id, application_key)
2018-07-29 09:42:03,979	15533	140570594121472	b2.account_info.sqlite_account_info	ERROR	_get_account_info_or_raise encountered a problem while trying to retrieve "account_id"
Traceback (most recent call last):
  File "/home/julle/anaconda2/lib/python2.7/site-packages/b2/account_info/sqlite_account_info.py", line 269, in _get_account_info_or_raise
    value = cursor.fetchone()[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
2018-07-29 09:42:03,980	15533	140570594121472	b2.account_info.sqlite_account_info	DEBUG	calling refresh_entire_bucket_name_cache(self=<b2.account_info.sqlite_account_info.SqliteAccountInfo object at 0x7fd921fcda90>) (hidden args: name_id_iterable)
2018-07-29 09:42:17,375	15533	140570594121472	b2.console_tool	ERROR	ConsoleTool account authorization error
Traceback (most recent call last):
  File "/home/julle/anaconda2/lib/python2.7/site-packages/b2/console_tool.py", line 253, in run
    self.api.authorize_account(realm, args.accountId, args.applicationKey)
  File "/home/julle/anaconda2/lib/python2.7/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/home/julle/anaconda2/lib/python2.7/site-packages/b2/api.py", line 126, in authorize_account
    response = self.raw_api.authorize_account(realm_url, account_id_or_key_id, application_key)
  File "/home/julle/anaconda2/lib/python2.7/site-packages/b2/raw_api.py", line 170, in authorize_account
    return self._post_json(realm_url, 'b2_authorize_account', auth)
  File "/home/julle/anaconda2/lib/python2.7/site-packages/b2/raw_api.py", line 166, in _post_json
    return self.b2_http.post_json_return_json(url, headers, params)
  File "/home/julle/anaconda2/lib/python2.7/site-packages/b2/b2http.py", line 302, in post_json_return_json
    return self.post_content_return_json(url, headers, data, try_count, params)
  File "/home/julle/anaconda2/lib/python2.7/site-packages/b2/b2http.py", line 275, in post_content_return_json
    response = _translate_and_retry(do_post, try_count, post_params)
  File "/home/julle/anaconda2/lib/python2.7/site-packages/b2/b2http.py", line 119, in _translate_and_retry
    return _translate_errors(fcn, post_params)
  File "/home/julle/anaconda2/lib/python2.7/site-packages/b2/b2http.py", line 55, in _translate_errors
    int(error['status']), error['code'], error['message'], post_params
ServiceError: 500 internal_error Unexpected exception
2018-07-29 09:42:17,380	15533	140570594121472	b2.console_tool	INFO	\\ ========================================  exit=1  ======================================== //

**Comment by bwbeach** [comment] 2018-07-29 14:10
Thanks for the thorough bug report.

I looked around on the service side, and things look like they are mostly working.  I did find a bug with these symptoms if you provide a bad accountId to `b2_authorize_account`.  We'll get that bug fixed this week.

In the meantime, a couple questions: 

1. Are you using the accountId and the master application key, or a key from the `create-key` command?
2. If you're using an accountId, can you double check that it's correct?
3. If the problems persist, could you contact the support team at Backblaze with your accountId, and we'll track down what the problem is.

**Comment by julled** [comment] 2018-07-29 14:32
Yes you are right, i used the application key, instead of the master app key. Maybe it should be written more clearly in docu / help of the cli tool. 
I try to use the keys for my restic backup but somehow there is nothing happening if i use the account id & app key ... but thats not the problem of backblaze. Thx anyway!

**Comment by mattsnowboard** [comment] 2018-08-09 07:25
+1 to fixing the documentation, I did the same thing

**Comment by julled** [comment] 2018-08-09 20:02
yes, also the restic tutorial should be updated https://help.backblaze.com/hc/en-us/articles/115002880514-How-to-configure-Backblaze-B2-with-Restic-on-Linux

**Comment by bwbeach** [comment] 2018-08-10 11:25
How is this update to the doc for authorize-account?

```
$ b2 help authorize-account

b2 authorize-account [<accountIdOrKeyId>] [<applicationKey>]

    Prompts for Backblaze accountID and applicationKey (unless they are given
    on the command line).

    You can authorize with either the master application key or
    a normal application key.

    To use the master application key, provide the account ID and
    application key from the "B2 Cloud Storage Buckets" page on
    the web site: https://secure.backblaze.com/b2_buckets.htm

    To use a normal application key, created with the create-key
    command or on the web site, provide the application key ID
    and the application key itself.

    Stores an account auth token in ~/.b2_account_info by default,
    or the file specified by the B2_ACCOUNT_INFO environment variable.

    Requires capability: listBuckets
```

**Comment by PeterNerlich** [comment] 2018-08-10 14:47
Okay, weird — I risk going off topic here, but I don't want to open a new issue because I think this is related. I seem to have gotten a lot of `ERROR: Unknown error: 401 unauthorized` since some point in the past (I run the script I made containing various b2 sync commands automated in the background) and just noticed. I tried renaming `~/.b2_account_info` and authorizing again, when I found *application keys*, which I didn't knew existed or had forgotten about (I think used the master key before) so I tried it. Updating with `pip` and building this always failed with `ERROR: unable to authorize account:  (unauthorized)`, until I found this, and, how lucky, you just committed the crucial information update to the doc.

Except that I still cannot sync. I didn't change anything on my script, and that authorization with the application key worked, but when my script calls e.g.

    b2 sync --allowEmptySource --excludeDirRegex ^programming/Asterisk/test --skipNewer /home/me/Documents b2://MY-BUCKET/home/me/Documents/

I get

    ERROR: Application key is restricted to bucket: MY-BUCKET

Is this known or some weird issue on my end again?

**Comment by bwbeach** [comment] 2018-08-10 14:54
I have a pending PR to fix this.  Sorry for the trouble.

**Comment by PeterNerlich** [comment] 2018-08-19 15:02
I still get an unauthorized error. Is this still related?

**Comment by bwbeach** [comment] 2018-08-20 17:36
Everything should be good with version 1.3.4

I would suggest double-checking the application key you're using: either accountId+masterKey or applicationKeyID+applicationKey.  If that looks good, and it's still not working, please contact Backblaze support.

**Closed** 2021-02-02 02:49 UTC
Labels: more-information-needed
