### ISSUE TITLE
b2 sync uploading multiple versions of same file (name, size, mtime, sha1)

### ISSUE THREAD

**Issue by bsdfox** [Backblaze/B2_Command_Line_Tool#187] opened 2016-07-08 15:13 UTC
EDIT: This is on freebsd.

We've been patiently waiting for a b2 sync to complete however once the bucket size reached 120% of the space used on our local filesystem I figured something fishy must be going on.
initially we were using simply
b2 sync /gpgencrypted b2:bucketname
but this appears to be storing lots of versions of files with the same name, sha1, mtime, size, etc.

Currently using this command which shows deleting several old versions of most files but I'm confident this will effectively require us to upload the entire dataset each time the sync is performed which isn't workable.
b2 sync --delete --replaceNewer /gpgencrypted b2:bucketname

Here's some proof that versions are being stored which shouldn't be-
b2 ls --versions --long bucketname TW/L855401/
                                                                                  -       -           -         -          0  TW/L855401/JPG/
4_z2c7aabca7148381f575d0913_f104c0232d0c55066_d20160611_m160621_c001_v0001001_t0009  upload  2016-06-11  16:06:21    2084028  TW/L855401/R1.rvg.gz.gpg
4_z2c7aabca7148381f575d0913_f104c0232d0c54df1_d20160611_m151042_c001_v0001001_t0009  upload  2016-06-11  15:10:42    2084028  TW/L855401/R1.rvg.gz.gpg
4_z2c7aabca7148381f575d0913_f11370448dc06ced5_d20160611_m134320_c001_v0001005_t0030  upload  2016-06-11  13:43:20    2084028  TW/L855401/R1.rvg.gz.gpg
4_z2c7aabca7148381f575d0913_f1016503cea87d951_d20160630_m184411_c001_v0001031_t0002  upload  2016-06-30  18:44:11    1184790  TW/L855401/S1.stv.gz.gpg
4_z2c7aabca7148381f575d0913_f11503294bf6cc80b_d20160706_m105903_c001_v0001031_t0024  upload  2016-07-06  10:59:03     895268  TW/L855401/S2.stv.gz.gpg
4_z2c7aabca7148381f575d0913_f11503294bf6cbfab_d20160706_m103757_c001_v0001031_t0024  upload  2016-07-06  10:37:57     895268  TW/L855401/S2.stv.gz.gpg
4_z2c7aabca7148381f575d0913_f112fc75022787bc8_d20160707_m122739_c001_v0001031_t0019  upload  2016-07-07  12:27:39     731285  TW/L855401/S3.stv.gz.gpg
4_z2c7aabca7148381f575d0913_f112fc75022787a2a_d20160707_m121210_c001_v0001031_t0019  upload  2016-07-07  12:12:10     731285  TW/L855401/S3.stv.gz.gpg
4_z2c7aabca7148381f575d0913_f1051ff7affa39bb9_d20160701_m002104_c001_v0001030_t0020  upload  2016-07-01  00:21:04     768038  TW/L855401/S4.stv.gz.gpg

    {
      "action": "upload",
      "contentLength": 1966134,
      "contentSha1": "92eaf3ad7c2575c7c0f83ed660ad360f39514f7d",
      "contentType": "application/octet-stream",
      "fileId": "4_z2c7aabca7148381f575d0913_f115fcf90544b6015_d20160610_m043625_c001_v0001018_t0022",
      "fileInfo": {
        "src_last_modified_millis": "1464206339532"
      },
      "fileName": "TW/L865301/R2.rvg.gz.gpg",
      "size": 1966134,
      "uploadTimestamp": 1465533385000
    },
    {
      "action": "upload",
      "contentLength": 1966134,
      "contentSha1": "92eaf3ad7c2575c7c0f83ed660ad360f39514f7d",
      "contentType": "application/octet-stream",
      "fileId": "4_z2c7aabca7148381f575d0913_f115fcf90544b5f3d_d20160610_m042705_c001_v0001018_t0022",
      "fileInfo": {
        "src_last_modified_millis": "1464206339532"
      },
      "fileName": "TW/L865301/R2.rvg.gz.gpg",
      "size": 1966134,
      "uploadTimestamp": 1465532825000
    },
    {
      "action": "upload",
      "contentLength": 1966134,
      "contentSha1": "92eaf3ad7c2575c7c0f83ed660ad360f39514f7d",
      "contentType": "application/octet-stream",
      "fileId": "4_z2c7aabca7148381f575d0913_f103635edb571ae3d_d20160610_m012153_c001_v0001026_t0027",
      "fileInfo": {
        "src_last_modified_millis": "1464206339532"
      },
      "fileName": "TW/L865301/R2.rvg.gz.gpg",
      "size": 1966134,
      "uploadTimestamp": 1465521713000
    },
    {
      "action": "upload",
      "contentLength": 1980296,
      "contentSha1": "eaaab933280a2d6c7a00f332756b932d60f71a30",
      "contentType": "application/octet-stream",
      "fileId": "4_z2c7aabca7148381f575d0913_f112dee9b049ec1df_d20160705_m145159_c001_v0001029_t0013",
      "fileInfo": {
        "src_last_modified_millis": "1464206340794"
      },
      "fileName": "TW/L865301/R3.rvg.gz.gpg",
      "size": 1980296,
      "uploadTimestamp": 1467730319000
    }
  ],
  "nextFileId": "4_z2c7aabca7148381f575d0913_f112dee9b049ec1e0_d20160705_m145159_c001_v0001029_t0013",
  "nextFileName": "TW/L865301/R3.rvg.gz.gpg"
}

**Comment by bwbeach** [comment] 2016-07-08 23:04
Thanks for the report!

We're just about to release a new version.  I'll try to get a fix for this in.

**Comment by bwbeach** [comment] 2016-07-08 23:13
Do you think the duplicates happened in one run of sync, or do you think the second copy happened when you ran sync again?

Is there any chance you had more than one sync running at a time?

**Comment by bsdfox** [comment] 2016-07-08 23:45
bwbeach,

Yes, due to poor planning on my part I did have multiple syncs of the same dataset happening concurrently.

**Comment by bwbeach** [comment] 2016-07-08 23:56
My guess is that's what caused the problem.  Do you think it's worth adding locking to warn people about that?

**Comment by bsdfox** [comment] 2016-07-09 00:16
Perhaps. I suspect a lot of people will be executing this from a cron job which could increase the likelihood of accidentally running multiple syncs simultaneously. At a minimum I would add a note somewhere indicating this could occur so preventative measures can be taken.

**Comment by bsdfox** [comment] 2016-07-09 17:12
bwbeach,

Saw your edit. Yes, adding per-file locking would be tricky because to prevent this you'd effectively have to keep each file locked until the sync process finished and then if something caused the python process to terminate early there would be erroneous lock files scattered about. 

I haven't looked into the b2 cloud API at all but if there was a way to query if an existing sync was running, or if it was possible to place a manual lock on a bucket yet allow access from a single unique event id (does the sync process generate this?) I could see this being a relatively straight-forward fix on the server side. 

Of course there's always just checking on the client side to see if a process is already running.. ps awuwx|grep "b2 sync" ... but this wouldn't be effective if different clients might execute syncs to the same bucket.

**Comment by ppolewicz** [comment] 2016-07-09 18:23
This too would be resolved implicitly by the daemon architecture.

@bwbeach: actually the system guarantees that file lock is removed upon a crash of any kind, so this is fairly easy to implement. Portalocker library exposes a cross-platform interface for this.

I don't really understand the requirement though. If I start async of `a/` to remote side, see in the log that the whole `a/a` already got synced (while `a/b` sync is still running), change something in `a/a` and run a new sync of `a/a`,  should the second sync fail immediately with an error?

What behavior exactly are we trying to prevent?

**Comment by bwbeach** [comment] 2016-07-09 18:25
I'm also not sure of the requirements.  The problem to solve is that a cron job running sync might start before the last incarnation is done, and could upload some of the same files again.

Should you be able to sync two different directories at the same time?  I think so.

What if one is a sub-directory of the other?

**Comment by ppolewicz** [comment] 2016-07-09 19:00
Maybe we can keep starting time of sync per directory in the local database and then only sync files created between the last remembered time and start of the current sync?

**Comment by bsdfox** [comment] 2016-07-17 18:41
I can verify that this is not a problem when two syncs aren't running concurrently.

**Comment by ppolewicz** [comment] 2016-07-26 22:02
This issue seems to be stuck with no decision on how to continue.

How about one of those, as a requirement:
- When a sync run is started, while another one, syncing the same local directory (absolute path), is already running, the new sync run shall fail with an appropriate error immediately
- When a sync run is started, while another one, syncing the same local directory (absolute path), is already running, the new sync run shall be delayed until the old sync job finishes (successfully or not)

The first one seems to be better. Does this properly describe what you have in mind, @bsdfox?

**Comment by bsdfox** [comment] 2016-07-29 14:17
I think it should fail immediately with an error.

**Comment by bwbeach** [comment] 2016-07-29 16:19
I agree.  Failing immediately is easier, and clearer.

**Comment by ppolewicz** [comment] 2016-08-01 18:32
@bsdfox, this issue is workaroundable by the user and very hard to implement reliably and without sacrificing performance in current code architecture of the CLI. Therefore we are not planning to work on it in the foreseeable future, unless the architecture is going to change (which may very well happen, but also not soon). Normally I'd ask if you want to implement it yourself and provide a pull request, but the changes needed to fulfill this requirement without making a monstrosity in the code are huge, so not really something an external contributor should do in their first contribution.

Also, you said yourself that the issue was mainly caused by the schedule which is now fixed, so currently lack of this causes no problem for any user. Therefore our current judgement is to drop this requirement until the situation changes.

**Closed by ppolewicz** 2016-08-01 18:32 UTC
