### ISSUE TITLE
Sync regularly fails with `Connection aborted: BadStatusLine`

### ISSUE THREAD

**Issue by TJC** [Backblaze/B2_Command_Line_Tool#435] opened 2018-04-03 01:38 UTC
I haven't been able to run 'b2 sync' for quite a while -- it always fails with the error below.
Not immediately - there's always a delay of a few minutes. I guess while it works out which files to sync or something?

Sometimes it'll upload one, maybe two, files, but mostly it fails on the first hurdle.
Files being uploaded are about 4mbyte on average, going over a 0.5 mbps ADSL connection. Yay, Australia ;( 

b2 version: 1.1.0

```
SYNCARGS="--threads 1 --delete --skipNewer --noProgress"
b2 sync $SYNCARGS \
    /a/path/here/ b2://bucketname-here/subdirectory/

ERROR:b2.console_tool:ConsoleTool command error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 1074, in run
_command
    return command.run(args)
  File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 857, in run
    allow_empty_source=allow_empty_source
  File "/usr/local/lib/python2.7/dist-packages/logfury/v0_1/trace_call.py", line 84, 
in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/sync.py", line 261, in sync_fo
lders
    source_folder, dest_folder, args, now_millis, reporter
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/sync.py", line 135, in make_fo
lder_sync_actions
    dest_file) in zip_folders(source_folder, dest_folder, reporter, exclusions, inclu
sions):
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/sync.py", line 93, in zip_fold
ers
    current_b = next_or_none(iter_b)
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/sync.py", line 36, in next_or_
none
    return six.advance_iterator(iterator)
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/folder.py", line 219, in all_f
iles
    self.folder_name, show_versions=True, recursive=True, fetch_count=1000
  File "/usr/local/lib/python2.7/dist-packages/b2/bucket.py", line 227, in ls
    self.id_, start_file_name, start_file_id, fetch_count
  File "/usr/local/lib/python2.7/dist-packages/b2/session.py", line 38, in wrapper
    return f(api_url, account_auth_token, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/b2/raw_api.py", line 370, in list_file
_versions
    maxFileCount=max_file_count
  File "/usr/local/lib/python2.7/dist-packages/b2/raw_api.py", line 139, in _post_jso
n
    return self.b2_http.post_json_return_json(url, headers, params)
  File "/usr/local/lib/python2.7/dist-packages/b2/b2http.py", line 299, in post_json_
return_json
    return self.post_content_return_json(url, headers, data, try_count, params)
  File "/usr/local/lib/python2.7/dist-packages/b2/b2http.py", line 272, in post_conte
nt_return_json
    response = _translate_and_retry(do_post, try_count, post_params)
  File "/usr/local/lib/python2.7/dist-packages/b2/b2http.py", line 116, in _translate
_and_retry
    return _translate_errors(fcn, post_params)
  File "/usr/local/lib/python2.7/dist-packages/b2/b2http.py", line 76, in _translate_
errors
    raise B2ConnectionError(str(e0))
B2ConnectionError: Connection error: ('Connection aborted.', BadStatusLine("''",))
ERROR: Connection error: ('Connection aborted.', BadStatusLine("''",))
```

**Comment by ppolewicz** [comment] 2018-04-03 02:05
@TJC it looks like it's your downlink, not uplink, which is causing the issue.

I think there is a bug, which sets the number of upload attempts to 1, disabling the retry mechanism. @bwbeach is there any reason for this? Which layer should set the number of attempts and what should it be set to?

**Comment by TJC** [comment] 2018-04-03 02:18
Is there any way to throttle the uploads?

As it stands, they swamp the connection, and things like DNS requests and ACKs struggle to get through.

**Comment by ppolewicz** [comment] 2018-04-04 01:54
#310 is about this, but it was not implemented yet.

You could try to use [trickle](https://linux.die.net/man/1/trickle) as a workaround.

**Comment by TJC** [comment] 2018-04-05 02:25
Thanks, I wasn't aware of `trickle` -- it seems to be doing the ... trick.
I still see intermittent b2 errors though -- I suspect it's just that the ADSL line drops during a transfer (as does, every few hours).

Although oh my word, uploading backups at 30kbyte/sec.. the chances of getting all the way through a 4gb file before an error occurs are not great. Does b2 retry failed multi-part uploads for long enough that an adsl connection can re-establish (say, 30-40 seconds)

**Comment by bwbeach** [comment] 2018-04-05 06:27
@ppolewicz - I don't know why the number of attempts is set to 1.  It should clearly be more!

When the number of attempts is set to something more reasonable, like 6, it might survive a 30-second outage.  The algorithm is to sleep 1.5^n seconds before each retry.  The sum of those times for 6 attempts is about 20 seconds.

**Comment by bwbeach** [comment] 2018-04-05 06:34
Update...

I reviewed more of the code I haven't looked at in a while.  The retries for uploads happen in `bucket.py`.  If the HTTP call fails, the failure goes back up to the upload method on the bucket, which will then get a different upload URL and try again.

**Comment by ppolewicz** [comment] 2018-04-05 06:48
ah yes, we have two retry mechanisms.

@TJC how many files are you uploading? Perhaps you should use more than 1 thread to improve bandwidth and a smaller part size to improve the chance of getting a file through?

**Comment by TJC** [comment] 2018-04-05 07:11
Smaller part sizes sounds good.. Where is that configured? There's nothing in `b2 help` or `b2 help sync`

I don't think increasing the thread count is a good plan! It will just divide the existing tiny bandwidth between more threads -- it can't improve the bandwidth of my upstream connection. right?

PS. Thanks for your help so far.

**Comment by ppolewicz** [comment] 2018-04-06 01:08
actually, on a high latency network, threads can (and probably will) improve your bandwidth. A single thread with high latency may not be able to fully utilize your connection due to how tcp works (you could think that each connection has its own speed limit which is caused by latency, that's sort of how it works). Try a few thread counts and see the total speed you get from it.

I'm not sure if `b2 sync` exposes the part size parameter, it is available in `b2 upload` as `--minPartSize` though. Perhaps you'd like to add that parameter to `b2 sync`, if you find it to be useful?

**Comment by stamster** [comment] 2018-05-07 07:42
Duplicity with b2 backend yields the same error:
> Attempt 1 failed. B2ConnectionError: Connection error: ('Connection aborted.', BadStatusLine("''",))

Sure, latency from Europe towards Backblace DC isn't best in the world, but we had no issues with backups via SFTP towards US West cast.

**Comment by ppolewicz** [comment] 2018-05-08 10:05
@stamster check the timeout and latency

**Comment by stamster** [comment] 2018-05-08 12:35
It's intermittent. So doesn't matter that much and I guess we can't do much about it.

**Comment by dima-ser** [comment] 2019-02-13 18:49
I'm experiencing the same issue. It's intermittent, but happens very often. Very frustrating. I'm paying for this and this is making re-evaluate B2 as my cloud storage solution.

**Comment by stamster** [comment] 2019-02-18 08:57
I'm afraid their Java back-end is having load issues, and not the HTTP/network. We still experience the issue using duplicity with b2. But it uses best effort strategy so eventually it succeeds after 2nd or 3rd retry.

**Comment by stamster** [comment] 2019-02-20 12:12
On Monday - it seems there was some major glitch, it took almost 7 hours to transfer 19 GB using 1 Gbit/s full duplex connection.

```
--------------[ Backup Statistics ]-------------- 
StartTime 1550457717.73 (Mon Feb 18 03:41:57 2019) 
EndTime 1550481995.06 (Mon Feb 18 10:26:35 2019) 
ElapsedTime 24277.33 (6 hours 44 minutes 37.33 seconds) 
SourceFiles 19 
SourceFileSize 20134041395 (18.8 GB) 
NewFiles 19 
NewFileSize 20134041395 (18.8 GB) 
DeletedFiles 0 
ChangedFiles 0 
ChangedFileSize 0 (0 bytes) 
ChangedDeltaSize 0 (0 bytes) 
DeltaEntries 19 
RawDeltaSize 20134037299 (18.8 GB) 
TotalDestinationSizeChange 20091992778 (18.7 GB) 
Errors 0 
------------------------------------------------- 
```

**Comment by stamster** [comment] 2019-03-11 09:35
Also experiencing the same issue but on a server hosted in US West, where latency shall be minimal.

```
--------------[ Backup Statistics ]-------------- 
StartTime 1552014445.70 (Fri Mar 8 04:07:25 2019) 
EndTime 1552048928.60 (Fri Mar 8 13:42:08 2019) 
ElapsedTime 34482.90 (9 hours 34 minutes 42.90 seconds) 
SourceFiles 18 
SourceFileSize 11645801995 (10.8 GB) 
NewFiles 18 
NewFileSize 11645801995 (10.8 GB) 
DeletedFiles 0 
ChangedFiles 0 
ChangedFileSize 0 (0 bytes) 
ChangedDeltaSize 0 (0 bytes) 
DeltaEntries 18 
RawDeltaSize 11645797899 (10.8 GB) 
TotalDestinationSizeChange 10649383725 (9.92 GB) 
Errors 0 
------------------------------------------------- 
```

So 9 and a half hours for 10 GB of data, something is not quite right.

**Comment by breucode** [comment] 2019-03-31 21:49
I have the same issue. On big files, (e.g. 4gb) this doesn't happen, but on many small files, this happens a lot. I am currently not able to download a 16gb backup.

**Comment by ppolewicz** [comment] 2019-03-31 22:26
@breucode this issue here is collecting various problems with BadStatusLine, but #562 is an identified bug that will be fixed pretty soon (though still it's going to be a few days). Restoring backup does not seem like something that can wait a few days. Can you wait?

**Comment by stamster** [comment] 2019-04-11 09:43
One more excerpt from our logs related to this topic.

```
Attempt 1 failed. MaxRetriesExceeded: FAILED to upload after 5 tries. Encountered exceptions: Connection error: ('Connection aborted.', error(104, 'Connection reset by peer')) 
500 internal_error Not enough members for write of 4_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: class org.apache.http.conn.HttpHostConnectException - Connect to member-06.vault:8180 [member-06.vault/192.168.243.16] failed: Connection refused (Connection refused)
neighbor_down; neighbor_down 
```

**Comment by ppolewicz** [comment] 2019-04-11 09:48
That one is a server-side error which indicates you have been writing to a nodeset which degraded below write threshold during the upload. It is a very rare case. Just retry. If it won't work, use the procedure from #531.

**Comment by dima-ser** [comment] 2019-04-12 00:08
> 
> 
> That one is a server-side error which indicates you have been writing to a nodeset which degraded below write threshold during the upload. It is a very rare case. Just retry. If it won't work, use the procedure from #531.

Except, it's failing almost every day for me. It's NOT a very rare case. Just checked the logs, and sure enough, failed today again.

**Comment by ppolewicz** [comment] 2019-04-12 21:27
@dima-ser you are hitting #562. @stamster has hit something else.

**Comment by ppolewicz** [comment] 2019-05-07 23:01
https://github.com/Backblaze/b2-sdk-python/pull/32 and https://github.com/Backblaze/b2-sdk-python/pull/22 fixed retries of download and metadata operations

**Closed by ppolewicz** 2019-05-07 23:01 UTC
Labels: bug, help wanted
