### ISSUE TITLE
Cannot install on Debian

### ISSUE THREAD

**Issue by jlbprof** [Backblaze/B2_Command_Line_Tool#630] opened 2020-06-03 00:55 UTC
```
root@lgarango01:/home/julian# pip3 install b2
Requirement already satisfied: b2 in /usr/local/lib/python3.5/dist-packages/b2-1.4.3-py3.5.egg
  Ignoring arrow: markers 'python_version <= "3.4"' don't match your environment
Collecting arrow>=0.8.0; python_version > "3.4" (from b2)
  Downloading https://files.pythonhosted.org/packages/99/b5/1f1c5ef3156f7b514c58613fe56e5670dc56374ab744bd1eb653c95e16b5/arrow-0.15.6-py2.py3-none-any.whl (47kB)
    100% |################################| 51kB 7.3MB/s 
Collecting b2sdk<1.2.0,>=1.1.0 (from b2)
  Could not find a version that satisfies the requirement b2sdk<1.2.0,>=1.1.0 (from b2) (from versions: 0.1.4, 0.1.6, 0.1.8, 1.0.0rc1, 1.0.0, 1.0.2)
No matching distribution found for b2sdk<1.2.0,>=1.1.0 (from b2)

```

**Comment by jlbprof** [comment] 2020-06-03 00:56
Same happens when installing on python2.7

**Comment by oliverdunk** [comment] 2020-06-06 16:34
Also seeing this following https://www.backblaze.com/b2/docs/quick_command_line.html with python2.7 and python3 on Ubuntu. @ppolewicz, could this be caused by https://github.com/Backblaze/B2_Command_Line_Tool/pull/616 perhaps?

**Comment by oliverdunk** [comment] 2020-06-06 16:37
For now, I worked around this by checking out fffd054af60c356e5bf11fdb9042a2bed5a10911, an older commit.

**Comment by ppolewicz** [comment] 2020-06-06 23:08
I think you are somehow using cli version from `master` branch which requires a version of b2sdk that was not released yet... but we have not released any cli versions with this requirement

**Comment by gbroiles** [comment] 2020-06-13 00:51
Installation (and the command line utility itself) works if you clone from https://github.com/Backblaze/b2-sdk-python and install that first - at least on Puthon 3.6 or later.

**Comment by gbroiles** [comment] 2020-06-13 01:00
The issue seems to arise because this page -

https://www.backblaze.com/b2/docs/quick_command_line.html

is the first search result on both Duck Duck Go and Google for "backblaze cli" - and the install instructions for other than OS X and Windows (e.g., Linux) suggest cloning from the master branch directly: 

"The alternative installation procedure is first make sure that you have Python installed, and then download the latest version of the source code from Github: [...]"

... but unless the user also clones from the master branch of b2-sdk-python, the version incompatibility arises. Looking at the history of changes to requirements.txt, it appears that the newer versions of b2-sdk are actually necessary, so removing the version limitation as a quick hack doesn't seem like a good choice.

**Comment by ppolewicz** [comment] 2020-06-17 12:20
This description needs to be changed to reflect the new reality after https://github.com/Backblaze/B2_Command_Line_Tool/pull/633 is merged. The chapter that shows how to install from git master should be removed.

**Comment by mjurbanski-reef** [comment] 2023-11-10 15:00
Instructions should be up to date now. Please note current version supports only Python >=3.7 or can be alternatively run under docker.

**Closed by mjurbanski-reef** 2023-11-10 15:00 UTC
