### ISSUE TITLE
b2 upload-file fails with  Unknown error: SysCallError(32, 'EPIPE')

### ISSUE THREAD

**Issue by carlmason** [Backblaze/B2_Command_Line_Tool#328] opened 2017-03-03 01:07 UTC
When I attempt to upload a 650GB file using  b2 upload-file it crashes after a few hours with the the mysterious messages shown below:
```
root@boserup:~# b2 upload-file --threads 8 Level0 /bruB2/galton_hdir-0/bru0 galton_hdir-0-B
/bruB2/galton_hdir-0/bru0:  47%|███████████████▏                | 329G/695G [2:52:41<3:11:58, 31.8MB/s]
ERROR: Unknown error: SysCallError(32, 'EPIPE')
root@boserup:~# b2 upload-file --threads 8 Level0 /bruB2/galton_hdir-0/bru0 galton_hdir-0-B
/bruB2/galton_hdir-0/bru0:  52%|███████████████████                  | 358G/695G [50:17<47:21, 119MB/s]
ERROR: Unknown error: SysCallError(32, 'EPIPE')
root@boserup:~# b2 upload-file --threads 8 Level0 /bruB2/galton_hdir-0/bru0 galton_hdir-0-B
/bruB2/galton_hdir-0/bru0:  65%|████████████████████▊           | 452G/695G [3:53:46<2:05:41, 32.2MB/s]
ERROR: Unknown error: SysCallError(104, 'ECONNRESET')
root@boserup:~# 
```

This has not happened smaller but othewise similar files uploaded from the same machine
( 10 year old 4 core opteron with 16GB )
The jobs restart nicely picking up where the last one left off,  but it would be nice if they finished normally instead.

**Comment by ppolewicz** [comment] 2017-03-03 01:10
This is an exact duplicate of #224

**Closed by ppolewicz** 2017-03-03 01:10 UTC
Labels: duplicate
