### ISSUE TITLE
Defaulting to 10 threads bad idea on consumer ADSL

### ISSUE THREAD

**Issue by TJC** [Backblaze/B2_Command_Line_Tool#228] opened 2016-09-13 03:55 UTC
In Australia, the vast majority of consumers have ADSL internet connections, with average upstream bandwidth around 0.7 mbit/sec. Yeah, I know, it sucks.

The b2 tool here seems to split big files into 100mbyte chunks, which it then tries to upload in up to ten simultaneous TCP streams.

This is disastrous. For an average Australian internet user, each of those streams will get 0.07 mbit/s each, or 7kbyte/sec. So it will take nearly four hours to complete -- and the b2 servers seem to give up and kick out connections that have lingered for a while.

Perhaps you could set threads to 1 by default, and suggest that users on high-bandwidth connections increase it? Or at least make it much clearer in the README that threads defaults to 10, which may be wildly inappropriate for low-bandwidth users?

Thanks!

**Comment by svonohr** [comment] 2016-09-13 06:07
Thanks for the report. I also wondered about the parallel uploading strategy a while ago. While it makes sense for lots of small files, where the overhead of connecting to the server is large, uploading large files with multiple threads doesn't increase the upload bandwidth. Instead many upload connections usually kill the internet performance for everyone else using the same internet connection. Maybe the number of parallel uploads should depend on the filesize?

**Comment by ppolewicz** [comment] 2016-09-13 14:30
I think this is somewhat similar to #200. It is not easy to implement a reliable automated mechanism that adapts to the (potentially dynamic) environment.
In theory, system could auto-diagnose itself and understand whether the current bottleneck is opening connections, the streaming speed, the hdd speed etc. It could also transfer files using a smart strategy, where if the bottleneck is on the network, and the file/part is about to be finished, then another thread is already started, so that the connection could be established in time to take over the network from the previous file (saving a few seconds of network bandwidth). We have not planned on working towards such optimizations (nor even on simple thread count adaptive mechanism) in the nearby future.

If other cloud storage CLIs don't offer such functionality and we could offer it, that could become an easily benchmarkable competitive advantage of B2 as a service.

@TJC: could you suggest an appropriate change to the README so that, at least, the user knows the thread count?

**Comment by svonohr** [comment] 2016-09-13 18:51
Another idea that came to mind: Do we keep the connection to the server alive for different requests? I believe we don't (or at least I couldn't find any code for it). Since it's just HTTPS it should be possible to keep the connection alive and avoid creating new expensive HTTPS connections. This also should reduce the number of required threads for fast syncing of lots of small files.

**Comment by ppolewicz** [comment] 2016-09-13 19:03
I assumed that keepalive was disabled because of server-side load balancing. @bwbeach ?

**Comment by bwbeach** [comment] 2016-09-13 20:28
Keep alive should be enabled.  And we're using the requests library in Python, which supports connection pooling.  AFAIK, connections are kept alive.

**Comment by bwbeach** [comment] 2016-09-16 00:37
I have confirmed that keep-alive is enabled in B2, and also that the command-line tool wasn't set up properly to use it.  I have submitted a pull request.

**Comment by TJC** [comment] 2016-09-16 00:57
Oh man, I can't believe we both made almost the same commits within minutes of each other! >.<

Mine has slightly different wording, and also changes the default to 1 thread.

**Comment by bwbeach** [comment] 2016-09-16 02:50
As you can probably tell, I'm reluctant to drop the default number of threads to 1.  For people with high-bandwidth connections, it works really well.

In fact, one of the reasons we added multiple threads to the Backblaze backup client is for customers in Australia.  The latency to California makes one thread slow, and adding threads helps to get around the problem.

I'll raise the issue with the product team at Backblaze and see what they think.

**Comment by bwbeach** [comment] 2016-09-16 02:51
BTW, I like your wording.  Nicely done.

**Comment by ppolewicz** [comment] 2016-09-16 12:15
While I understand that some users from Australia may want to use one thread, the **default** value should be set to what **most** users want.

Unless most b2 users actually are located in Australia or Australia-like (network-wise) places, then the default thread amount should not be reduced to 1.

**Comment by bwbeach** [comment] 2016-09-16 19:09
I agree with @ppolewicz about the default.  I'll merge @TJC's pull request, because the wording is nice, and then change the default back to 10.

**Comment by ppolewicz** [comment] 2016-09-16 23:14
@TJC do you think we can close this now, or is there still something left to be done?

**Comment by TJC** [comment] 2016-09-19 00:53
We could sort this out so that everyone is happy, if the threading system could be tuned to only apply to small files.

Maybe when a >500kbyte file is being transferred, a global lock or semaphore is acquired, and only released at the end of the upload process. Small files do not try to acquire the semaphore/lock, but do wait for it to be available before commencing their transfer.

I get that maybe this is a lot of work for what seems like a small number of users, but we did agree earlier that it's pointless or even counter-productive to be using multiple threads on large uploads. (Certainly doesn't interact well with other users of shared bandwidth)

**Comment by ppolewicz** [comment] 2016-09-19 01:25
This would be detrimental to users that have a bunch of 501KB files and a high latency.

ADSL users from Australia should set their `threads` parameter properly. This is not an instruction specific for that continent - since we don't provide automatic setting of the amount of threads, every user should configure the parameter properly to achieve best results.

> but we did agree earlier that it's pointless or even counter-productive to be using multiple threads on large uploads

no. There are practical limits to TCP connections, so sometimes there is better to have more of them.

**Closed** 2023-10-04 08:08 UTC
