### ISSUE TITLE
Needs option to not follow links

### ISSUE THREAD

**Issue by raindog308** [Backblaze/B2_Command_Line_Tool#390] opened 2017-11-04 17:55 UTC
The 'b2 sync' command follows links and treats them as if they are simply directory paths.

It should either

- not follow links and report them as things it couldn't back up (which is what rclone does)

- follow them but give an option not to follow

Otherwise, a single ln command can radically alter backups.

I'm aware of exclude regex but that is a very crude tool and doesn't provide forward security...e.g., every time you symlink (or software you install unknowingly symlinks), you have to modify the backup script.

**Comment by bwbeach** [comment] 2017-11-05 21:25
This would be a good option to have.

Another thing that occurred to me is the possibility of storing symlinks in B2 by adding to the "file info" to say it's a symlink, and putting the contents of the link in the file.

Would you be interested, @raindog308, in looking at implementing this?  We have a group of friendly people on this project who would be happy to answer questions and offer advice.

**Comment by dmanikowski-reef** [comment] 2017-11-06 17:23
I can take it if @raindog308 does not want to :)

**Comment by bhygate** [comment] 2018-01-01 20:07
Dupe of #280?

Deffo needed though B-)

**Comment by dmanikowski-reef** [comment] 2018-01-02 12:09
We are almost done with it. Needed to do large code refactoring and there was a large discussion within our internal review.

**Comment by claudio5678** [comment] 2018-05-11 14:43
Nice to know it's almost done, can you provide an estimate date for it? thanks!

**Comment by ppolewicz** [comment] 2018-05-11 20:52
I think that got abandoned a few months ago, before it got finished...

**Comment by joshlewis** [comment] 2018-10-05 05:18
I just hit some circular symlinks deep inside a hard drive I'm trying to back up. That was a huge pain to discover and fix. Please give me the option to not follow them! 🙏

**Comment by zackse** [comment] 2018-10-05 19:09
@ppolewicz and @bwbeach can this issue be closed now that PR #512 is merged?

**Comment by bwbeach** [comment] 2018-10-05 19:15
Closing.  #512 fixed this problem.

**Closed by bwbeach** 2018-10-05 19:15 UTC
Labels: up-for-grabs
