### ISSUE TITLE
Using it as a Python library

### ISSUE THREAD

**Issue by mohmad-null** [Backblaze/B2_Command_Line_Tool#254] opened 2016-10-03 09:29 UTC
How about allowing the CLT to also be used as a Python API/Library? The core functions are all already there, they just need to be exposed/documented.

I did see - https://github.com/Backblaze/B2_Command_Line_Tool/issues/147 - which may or may not be suggesting the same thing.

**Comment by ppolewicz** [comment] 2016-10-03 09:42
The functions are already exposed. One can see how to use it by reading code of tests and `ConsoleTool`, which is an example implementation of a tool using the Python API. In fact the `b2_fuse` guys are moving from their native implementation to our api.

**Comment by ppolewicz** [comment] 2016-10-03 09:52
This is a duplicate of #4 and #147. If you could help on #147, it would be much appreciated.

**Comment by mohmad-null** [comment] 2016-10-03 19:22
Thanks; I managed to coble something together from that. My OO is no-where near good enough to be of any use with even documenting I'm afraid.

**Comment by ppolewicz** [comment] 2016-10-03 22:13
The help we need is with setting up Sphinx, not with object oriented design. I imagine it might be a challenge for you though, since you use Windows.

by the way, if there is nothing else to discuss here, please close this issue.

**Closed** 2016-10-13 21:54 UTC
Labels: duplicate
