### ISSUE TITLE
Feature request :  Ability to auto delete files after X time

### ISSUE THREAD

**Issue by khavishbhundoo** [Backblaze/B2_Command_Line_Tool#333] opened 2017-03-27 07:25 UTC
It would be great if backblaze could implement a feature where files get automatically deleted based on a header.`x-bz-delete-timestamp` or something similar could be added to files upon upload

**Comment by ppolewicz** [comment] 2017-03-27 12:10
Is the `--keepDays` option of `sync` and (lifecycle rules)[https://www.backblaze.com/b2/docs/lifecycle_rules.html] not sufficient?

**Comment by svonohr** [comment] 2017-03-27 16:12
I suppose he wants lifecycle rules on a per file basis. With 100 rules per bucket you can't add a rule for every file.

**Comment by khavishbhundoo** [comment] 2017-03-28 05:00
Sorry for the late reply guys .....@svonohr is perfectly right

**Comment by ppolewicz** [comment] 2017-03-28 09:36
@khavishbhundoo would you take a shot at implementing it? 

We encourage outside contributors to perform changes on our codebase. Many such changes have been merged already. In order to make it easier to contribute, core developers of this project:

* provide guidance (through the issue reporting system)
* provide tool assisted code review (through the Pull Request system)
* maintain a set of integration tests (run with a production cloud)
* maintain a set of (well over a hundred) unit tests
* automatically run unit tests on 14 versions of python (including osx, Jython and pypy)
* format the code automatically using [yapf](https://github.com/google/yapf)
* use static code analysis to find subtle/potential issues with maintainability
* maintain other Continous Integration tools (coverage tracker)

**Comment by demlasjr** [comment] 2017-04-04 23:47
I need file age delete feature too. I even asked for Twitter few weeks ago.
I'm uploading files with this format

name1_year_month_day.zip
name2_year_month_day.zip

The problem is.....this doesn't count as versioning, so after days/months I have hundreds of name1 and name2 files, each one with different date. I need a way to automatically delete them X days after being uploaded. I could done that in Google Cloud and Amazon S3 👎

**Comment by bwbeach** [comment] 2017-04-05 00:55
You can set up Lifecycle Rules [https://www.backblaze.com/b2/docs/lifecycle_rules.html] to hide an then delete files a given number of days after uploading.

**Comment by demlasjr** [comment] 2017-04-05 02:15
I already tried but that option works only for versions, not files without versions

**Comment by ppolewicz** [comment] 2017-04-05 09:41
You can write a file with one name every day and then it will work.

**Comment by bwbeach** [comment] 2017-04-05 19:03
With Lifecycle Rules, you can set up a rule to hide files after a number of days, and then a rule to delete hidden files after a day.  That should clean up your old files.

You need to be careful, though, with `daysFromUploadingToHiding` like this, in conjunction with `daysFromHidingToDeleted`.  All of your files will age out and get deleted.

**Closed** 2019-05-07 23:32 UTC
Labels: enhancement, help wanted

**Comment by Anas-Qadil** [comment] 2024-06-10 10:16
i need something like this, to upload a file and set retention time in header so the file will be auto deleted after a period of time, im doing daily  snapshot backups and i want the backup files to be deleted after like a week

**Comment by ppolewicz** [comment] 2024-06-10 12:20
@Anas-Qadil there is a feature for this already, it's called Lifecycle Rules

**Comment by Anas-Qadil** [comment] 2024-07-01 17:09
@ppolewicz, the issue was that the prefix setting applies to the whole bucket, not to individual files. I tried to find a way to do it without making a new bucket, but I couldn't find any solution. So, I ended up making a new bucket. 😄
