### ISSUE TITLE
Respect XDG Base Directory specification

### ISSUE THREAD

**Issue by samhh** [Backblaze/B2_Command_Line_Tool#699] opened 2021-04-04 11:30 UTC
It looks like B2 CLI dumps a couple of files into `$HOME` on Linux, for example `.b2_account_info`.

Ideally it would conform to the [aforementioned specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). I'm not familiar with the Python ecosystem but I suppose you could utilise something like [srstevenson/xdg](https://github.com/srstevenson/xdg).

Cheers! :slightly_smiling_face:

**Comment by ppolewicz** [comment] 2021-04-04 21:48
This is a duplicate of https://github.com/Backblaze/b2-sdk-python/pull/129 which is already implemented and is going to be released soon with b2sdk apiver v2.

**Closed by ppolewicz** 2021-04-04 21:48 UTC
Labels: duplicate
