### ISSUE TITLE
Allow users to specify the location of the b2_account_info

### ISSUE THREAD

**Issue by khavishbhundoo** [Backblaze/B2_Command_Line_Tool#298] opened 2016-12-14 18:10 UTC
I am trying to use b2 commandline in my php application with `shell_exec`.An option such as `--auth_info_path` help to allow a custom path for the b2_account_info.This will help a lot especially when doing uploads

**Comment by ppolewicz** [comment] 2016-12-14 18:50
You can use it like this: `B2_ACCOUNT_INFO=/path/to/b2_account_info b2 upload_file ...`

If that solves your problem, please close this issue.

**Comment by khavishbhundoo** [comment] 2016-12-14 20:15
Thanks for the quick help 

I am getting the following now

`/usr/bin/b2", line 9, in load_entry_point('b2==0.6.8', 'console_scripts', 'b2')() File "/usr/lib/python2.7/site-packages/b2/console_tool.py", line 996, in main exit_status = ct.run_command(decoded_argv) File "/usr/lib/python2.7/site-packages/b2/console_tool.py", line 887, in run_command return command.run(args) File "/usr/lib/python2.7/site-packages/b2/console_tool.py", line 805, in run bucket = self.api.get_bucket_by_name(args.bucketName) File "/usr/lib/python2.7/site-packages/b2/api.py", line 177, in get_bucket_by_name for bucket in self.list_buckets(): File "/usr/lib/python2.7/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper return function(*wrapee_args, **wrapee_kwargs) File "/usr/lib/python2.7/site-packages/b2/api.py", line 198, in list_buckets response = self.session.list_buckets(account_id) File "/usr/lib/python2.7/site-packages/b2/session.py", line 42, in wrapper reauthorization_success = self._api.authorize_automatically() File "/usr/lib/python2.7/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper return function(*wrapee_args, **wrapee_kwargs) File "/usr/lib/python2.7/site-packages/b2/api.py", line 107, in authorize_automatically self.account_info.get_application_key(), File "/usr/lib/python2.7/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper return function(*wrapee_args, **wrapee_kwargs) File "/usr/lib/python2.7/site-packages/b2/api.py", line 133, in authorize_account realm, File "/usr/lib/python2.7/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper return function(*wrapee_args, **wrapee_kwargs) File "/usr/lib/python2.7/site-packages/b2/account_info/sqlite_account_info.py", line 173, in set_auth_data conn.execute('DELETE FROM account;') sqlite3.OperationalError: unable to open database file `

**Comment by ppolewicz** [comment] 2016-12-14 21:09
It looks like the path to database does not exist

**Comment by bwbeach** [comment] 2016-12-15 01:19
There could be a permission problem.  If php can't create the file in the given place, or the directory doesn't exist, it will get an error.

I have not yet been able to reproduce this error exactly, but I have gotten similar errors when lacking write permission to the directory or to the file.

**Comment by khavishbhundoo** [comment] 2016-12-15 05:45
It was indeed a permission issue.Thanks for the help bwbeach

**Closed** 2016-12-15 06:03 UTC
Labels: question
