### ISSUE TITLE
 AttributeError: 'InMemoryAccountInfo' object has no attribute 'get_minimum_part_size'

### ISSUE THREAD

**Issue by rafaelteb** [Backblaze/B2_Command_Line_Tool#727] opened 2021-06-04 14:34 UTC
Hi there!
Could you help me out here? Probably a small mistake I made somewhere.
I am running b2 with duplicity on a ton of servers and almost never had any serious issues.
And now I get this error when running a restore script.sh with root user (which stresses me a bit):
````
Traceback (innermost last):
  File "/usr/local/bin/duplicity", line 100, in <module>
    with_tempdir(main)
  File "/usr/local/bin/duplicity", line 86, in with_tempdir
    fn()
  File "/usr/local/lib/python3.8/dist-packages/duplicity/dup_main.py", line 1525, in main
    action = commandline.ProcessCommandLine(sys.argv[1:])
  File "/usr/local/lib/python3.8/dist-packages/duplicity/commandline.py", line 1188, in ProcessCommandLine
    backup, local_pathname = set_backend(args[0], args[1])
  File "/usr/local/lib/python3.8/dist-packages/duplicity/commandline.py", line 1059, in set_backend
    globals.backend = backend.get_backend(bend)
  File "/usr/local/lib/python3.8/dist-packages/duplicity/backend.py", line 225, in get_backend
    obj = get_backend_object(url_string)
  File "/usr/local/lib/python3.8/dist-packages/duplicity/backend.py", line 211, in get_backend_object
    return factory(pu)
  File "/usr/local/lib/python3.8/dist-packages/duplicity/backends/b2backend.py", line 103, in __init__
    (self.path, bucket_name, self.service.account_info.get_minimum_part_size()), log.INFO)
 AttributeError: 'InMemoryAccountInfo' object has no attribute 'get_minimum_part_size'


````
My restore script:

````
B2_ACCOUNT="adfadfd"
B2_KEY="dafadfdfdf"
B2_BUCKET="some bucket"
B2_DIR="/filestructures"
B2_DB_DIR="/databasedumps"
B2_RESTORE="/"

# Local directory to restore to
LOCAL_DIR="/opt/restored_backups/restore/filestructures/"
LOCAL_DB_DIR="/opt/restored_backups/restore/databasedumps/"

# GPG key (last 8 characters of public fingerprint!) “sudo gpg --fingerprint”
ENC_KEY="dfadf"
SGN_KEY="dsfadf"
export PASSPHRASE="sdfda"
export SIGN_PASSPHRASE="dafsdfd"

# Restore last backup: filestructures
# Important: in b2... at the end the folder after a slash has to be indicated!
duplicity \
restore \
--sign-key $SGN_KEY \
--encrypt-key $ENC_KEY \
--file-to-restore=${B2_RESTORE} \
b2://${B2_ACCOUNT}:${B2_KEY}@${B2_BUCKET}/${B2_DIR} ${LOCAL_DIR}

# Restore last backup: databases
duplicity \
restore \
--sign-key $SGN_KEY \
--encrypt-key $ENC_KEY \
--file-to-restore=${B2_RESTORE} \
b2://${B2_ACCOUNT}:${B2_KEY}@${B2_BUCKET}/${B2_DB_DIR} ${LOCAL_DB_DIR}

# Unset variables
unset B2_ACCOUNT
unset B2_KEY
unset B2_BUCKET
unset B2_DIR
unset B2_DB_DIR
unset LOCAL_DIR
unset LOCAL_DB_DIR
unset B2_RESTORE
unset ENC_KEY
unset SGN_KEY
unset PASSPHRASE

````

my versions and OS types and stuff:

````
duplicity 0.8.12
Python 3.8.5
b2 command line tool, version 2.5.0
OS: Ubuntu 20.04.2 LTS x86_64
````

**Comment by ppolewicz** [comment] 2021-06-05 02:31
Duplicity incorrectly used our public API. You might want to install an older version of `b2sdk` or b2 cli for now, but generally you should ask duplicity to fix their code and release a new version which uses a proper import structure which does not end in this error.

This is a duplicate of https://github.com/Backblaze/b2-sdk-python/issues/251

**Closed by ppolewicz** 2021-06-05 02:31 UTC
