### ISSUE TITLE
3.0.2 binary not working 

### ISSUE THREAD

**Issue by AMKamel** [Backblaze/B2_Command_Line_Tool#754] opened 2021-09-27 08:52 UTC
I installed the linux release then running the command gives the following error 
```
[8339] Error loading Python lib '/tmp/_MEIX3M7jE/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not fou
nd (required by /tmp/_MEIX3M7jE/libpython3.9.so.1.0)      
```

This error is not there on version 3.0.1

**Comment by mlech-reef** [comment] 2021-09-27 14:59
Duplicate of #750

@AMKamel, the fix is already on `master` but not yet released

**Comment by mlech-reef** [comment] 2021-09-27 16:58
https://github.com/Backblaze/B2_Command_Line_Tool/releases/tag/v3.0.3 has been released!

It should fix your problem

**Closed by mlech-reef** 2021-09-27 16:58 UTC
Labels: duplicate
