### ISSUE TITLE
b2 upload-file resume/restart on default/high thread count

### ISSUE THREAD

**Issue by nathanverrilli** [Backblaze/B2_Command_Line_Tool#509] opened 2018-09-13 20:16 UTC
add a retry/resume option so that a broken connection restarts automatically

**Comment by ppolewicz** [comment] 2018-09-13 20:43
First, b2 upload-file already retries a few times before giving up.

Second, when a large file is being uploaded and fails, on another attempt to upload the same file, parts which were completed should not be sent again... So I think your requirement actually is already implemented. Or do you mean something else?

**Comment by ppolewicz** [comment] 2019-01-24 23:32
@mariobaldini see [here](https://github.com/Backblaze/B2_Command_Line_Tool#detailed-logs) for info on how to enable detailed logs.
`Connection aborted.', BadStatusLine("''",)` usually means that the connection broke off before server could send any data back to you due to a timeout (on either side).

Are you using upload or sync?

I'd be very interested to see the relevant part of the logs - there are plans to increase reliability of uploads very soon, so any information about real-life case you could provide would be very helpful.

**Comment by mariobaldini** [comment] 2019-01-24 23:53
```
echo "Uploading to remove server..."
find /backups/seafile/latest/*.tgz -printf "%f\n" | xargs -I {} b2 upload-file BackupCSU /backups/seafile/latest/{} seafile/{}
```

This is the exact line of my script. It upload some files to a specific bucket. The failure happens sometimes only in the big one (~150GB).

Also, I noticed that the sha1 hash is not being displayed in the web interface, only for the big file. 

At first I thought it could be some system lag due the file size, but it still don't show up after multiple hours. If I'm not mistaken I read somewhere in the b2 documentation that files are always checksumed in the origin, to compare with the uploaded one and guarantee that no errors occurred. 

If this is true, there should be no lag in the web display... since the hash must be calculated right after the upload (and before the b2 session ends), so it can confirm its correctness and re-upload as needed. IMHO

**Comment by ppolewicz** [comment] 2019-01-25 10:16
> Also, I noticed that the sha1 hash is not being displayed in the web interface, only for the big file.
That's #539. 

Without `--debugLogs` it is hard to say whether the retries happened and how much of them were there.


The use case that you have here is a little odd though: you are sending the files sequentially using find and `upload-file`, when the intended way to do it would be via `sync` and `--includeRegex`. Is there a reason you prefer the operation to be performed sequentially for each file rather than in parallel, but not via `--threads 1`?

The larger idea behind running this as a sync operation is that we might have a much better failure tolerance algorithm (which would realize the connection status has been broken as multiple transfers have been interrupted at roughly the same time), including new parameters which would allow the user to specify, for example, the length of the backup window (so if there is no network for an hour for some reason, properly configured sync might patiently wait rather than crashing down).

**Comment by tristanbrown** [comment] 2019-03-03 04:14
The b2 CLI certainly does not resume interrupted uploads of large files, neither using `sync` nor `upload-file`.

**Comment by ppolewicz** [comment] 2019-03-03 15:38
@tristanbrown I'm pretty sure that it does, but if you can reproduce a scenario where resuming a large file upload has not skipped uploading already completed parts, then please provide logs for such case and we will fix it.

**Comment by tristanbrown** [comment] 2019-03-04 16:45
Started an upload of a 1.14 GB .pdf file in a folder at `Dir` using `b2 sync --debugLogs Dir bucket:Dir`. Waited until the progress tracker showed 0.61 GB had uploaded. Closed the terminal to terminate the process. At this point, the B2 web interface shows a "started large file" version of this file in `bucket:Dir`, with a "Size" of 0 bytes, an "Uploaded Parts Size" of 0 bytes, and a "Sha1" of "none." Yet, 0.6 GB of additional total data is measured at the bucket level. 

I then try to resume the upload using the same `sync` command in a new terminal. The upload starts from 0.00 / 1.14 GB uploaded. A second "started large file" version is created at `bucket:Dir`, even if I disable versioning in this bucket. No parts are skipped. 

After allowing the full 1.14 GB upload to complete, the web interface shows the completed file in `bucket:Dir`, in addition to the first "started large file" version. 

The logs from before and after interrupting the process are attached. 

[b2_cli_before_interrupt.log](https://github.com/Backblaze/B2_Command_Line_Tool/files/2927339/b2_cli_before_interrupt.log)
[b2_cli_after_interrupt.log](https://github.com/Backblaze/B2_Command_Line_Tool/files/2927344/b2_cli_after_interrupt.log)

**Comment by ppolewicz** [comment] 2019-03-04 17:34
@tristanbrown from your description it looks like you have used (a default of) 10 threads to run the upload, so all of them were at ~61 MB / 100MB of uploading a part when you terminated the process, so no parts were actually completed.

In such scenario, please try to add `--threads X` where X is between 1 and 5. You could also try `b2 upload-file` with a `--minPartSize` set to 50MB (and `--threads`).

**Comment by tristanbrown** [comment] 2019-03-04 18:29
Indeed, setting `--threads 1` does allow the resume to take place properly, as parts are uploaded one after another. Perhaps this should be the default for large file uploads? What's the point of chunking a file if the upload is multi-threaded anyways? If processor power were the bottleneck, this would make sense, but I think for large files, bandwidth and RAM are the bigger concerns.

**Comment by ppolewicz** [comment] 2019-03-05 11:20
Users on high latency networks (especially from 🇦🇺 and 🇳🇿, but 🇵🇱 also has excessive ping to B2) are hitting a tcp latency wall (where there is a limit of how much data you can push out through a singl socket). Users on low latency networks usually don't suffer from a high thread count and I'd expect their connection to be pretty stable. Worst case, they can just adjust the thread count.

I don't know how to properly judge how the default thread count should be set, maybe it's 8, maybe 10, maybe 2... Undoubtedly some users will have to manually adjust the thread count, regardless of how we will set the default. The goal here would be to minimize the amount of users that need to alter the configuration to get the command to a usable state. There haven't been many complaints about the thread count being too high.

In a perfect world, we could implement an adaptive mechanism that would adjust the thread count dynamically to maximize throughput, but minimize the number of parts transferred concurrently, but that's a lot of coding and, IMO, not really a lot of value, so I'd rather not do it at this point, unless some new information is brought into light.

**Closed** 2019-04-25 21:39 UTC
Labels: question
