### ISSUE TITLE
Using sync to keep a folder in sync

### ISSUE THREAD

**Issue by oligriffiths** [Backblaze/B2_Command_Line_Tool#564] opened 2019-04-04 16:29 UTC
Hi

Is it possible to have a folder kept in sync and changes in that folder be automatically uploaded and downloaded?

I want to share a folder (dropbox style) between 2 macs, can I use b2 to do this?

Thanks

Oli

**Comment by oligriffiths** [comment] 2019-04-04 21:55
Additionally, when using `sync` to download, I am getting the following exception many times
```
AssertionError
b2_download(_Serato_/soundcloud_window.pref, 4_z0b911d5f1354e7986c980f1e_f1006cac3930d1c2c_d20190404_m160629_c001_v0001117_t0054, /Users/goli/Music/test/_Serato_/soundcloud_window.pref, 1554322787000): AssertionError()
ERROR:b2.sync.action:an exception occurred in a sync action  3.17 MB/s
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/b2/sync/action.py", line 42, in run
    self.do_action(bucket, reporter)
  File "/usr/local/lib/python2.7/site-packages/b2/sync/action.py", line 143, in do_action
    bucket.download_file_by_name(self.b2_file_name, download_dest, SyncFileReporter(reporter))
  File "/usr/local/lib/python2.7/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python2.7/site-packages/b2/bucket.py", line 168, in download_file_by_name
    url, download_dest, progress_listener, range_
  File "/usr/local/lib/python2.7/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python2.7/site-packages/b2/transferer/transferer.py", line 108, in download_file_from_url
    file, response, metadata, self.session
  File "/usr/local/lib/python2.7/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python2.7/site-packages/b2/transferer/simple.py", line 24, in download
    actual_size = self._get_remote_range(response, metadata).size()
  File "/usr/local/lib/python2.7/site-packages/b2/transferer/abstract.py", line 51, in _get_remote_range
    return Range(0, metadata.content_length - 1)
  File "/usr/local/lib/python2.7/site-packages/b2/transferer/range.py", line 18, in __init__
    assert 0 <= start <= end
```

**Comment by oligriffiths** [comment] 2019-04-04 21:57
It seems that a 0 range is being passed https://github.com/Backblaze/B2_Command_Line_Tool/blob/6e9bcc0dd7e5b54b4e99d483e77f6259da8f30eb/b2/transferer/abstract.py#L51 which causes the exception due to a check in the Range class.

**Comment by oligriffiths** [comment] 2019-04-04 22:09
PR to fix https://github.com/Backblaze/B2_Command_Line_Tool/pull/565

**Comment by ppolewicz** [comment] 2019-04-06 14:33
You could implement a dropbox-like sync by using sync on b2sdk or b2cli layer, but you would probably need to use inotify to make it efficient.

I'm not sure if such functionality should be included in b2sdk or b2cli package, but I'm leaning into *yes* and *in both*.

Is this something you would like to contribute? We provide quite a lot of support for contributors in both projects, though still, it is not a small feature.

**Comment by oligriffiths** [comment] 2019-04-06 19:01
@ppolewicz is there a way to get a notification from the b2 server when a new file is added? I feel like you would need notifications from both the local file system and the remote.

**Comment by ppolewicz** [comment] 2019-04-06 19:03
You could journal the changes you upload from the first client and poll the journal from the second client

**Comment by oligriffiths** [comment] 2019-04-06 19:08
Yeah I guess that's a reasonable strategy. Probably make a directory and write a new file for each changed file, with a date marker in the filename, then individual files can be synced and cleared from the directory, this would save changes happening on both machines simultaneously and not having to deal with a single journal and conflicts

**Comment by ppolewicz** [comment] 2019-04-07 21:50
I can't see any commercial sense in it unless a real journal is added, and for hobby-type usage, B2 might not be the best choice given a few free alternatives that are easily available (as you mentioned).

I've actually researched this, the issue is that if you assume a client can get CPU-starved (due to cpu steal in virtualization, for example), you are running into a stop problem where it is impossible to say if another thread will do something (as it may be starved and in a middle of an operation) or not. It IS possible to get a consistent multi-node semaphore using B2, but getting a consistent journal is still a lot of work.

**Comment by ppolewicz** [comment] 2019-12-16 19:55
This was fixed when https://github.com/Backblaze/b2-sdk-python/pull/13 was merged

**Closed by ppolewicz** 2019-12-16 19:55 UTC
