### ISSUE TITLE
b2 sync: b2sdk.exception.ChecksumMismatch: sha1 checksum mismatch -- bad data

### ISSUE THREAD

**Issue by iameli** [Backblaze/B2_Command_Line_Tool#666] opened 2020-10-27 22:15 UTC
I have about 12mb of video files in `b2://livepeer-staging-us-west/b81cv9w62biizxyf`. I'd like to download them. I did this:

```
b2 sync b2://livepeer-staging-us-west/b81cv9w62biizxyf .
```

And that results in lots and lots of `b2sdk.exception.ChecksumMismatch: sha1 checksum mismatch -- bad data` messages. Am I doing something wrong? [Full logs are here.](https://gist.github.com/iameli/94132d5809c4e3e261394695e1e0d766)

**Comment by ppolewicz** [comment] 2020-10-28 11:31
It looks like a duplicate of #657. Do you know how to install and use new b2sdk that has the fix for it?

**Closed** 2020-11-11 11:32 UTC
Labels: duplicate, more-information-needed
