### ISSUE TITLE
Add ability to rename files once uploaded

### ISSUE THREAD

**Issue by macbookandrew** [Backblaze/B2_Command_Line_Tool#57] opened 2016-02-04 20:16 UTC
Is it possible to rename files once they’ve been uploaded? I’ve several times uploaded a 500MB+ file only to discover that I mistyped the remote filename and don’t want to have to re-upload the entire file just to change the filename…

**Comment by bwbeach** [comment] 2016-02-04 22:16
I'm afraid that the B2 service does not have a way to rename a file.  So this tool that uses that service can't do it either.

**Comment by macbookandrew** [comment] 2016-02-05 01:04
Any chance of that being implemented? Since files are apparently stored using fileids, is the filename a piece of metadata?

**Comment by nilayp** [comment] 2016-02-05 17:52
Andrew - This has been requested and is on our feature list for future consideration. Thanks for your feedback.

-- Nilay

**Comment by macbookandrew** [comment] 2016-02-05 17:54
:+1:

**Comment by lastdates** [comment] 2016-06-26 20:33
hi Nilay,
any timeline by when will file rename be available?

**Comment by jonhoo** [comment] 2019-06-17 03:26
Any updates on whether this will make it onto the roadmap? A number of other issues are being closed as duplicates of this, yet this is still marked as closed?

**Comment by nathanverrilli** [comment] 2019-06-17 04:23
There is no renaming of immutable objects, that’s what immutable is all about.

Rename is a copy-and-delete operation, and the copy API is now in beta. We will add that functionality to the B2 CLI soon-ish. This week? Probably not. Next week? Maybe, maybe not. By the end of this month? Maybe. End of next month? Likely. It’s certainly on our roadmap.

However, it’s lower priority than a number of other changes to the CLI and SDK. I’d love to hear your use case for it — and that helps us prioritize this stuff.

Cheers,
Nathan

**Comment by jonhoo** [comment] 2019-06-17 13:22
@nathanverrilli I'm perfectly happy with server-side copy + delete. It is functionally equivalent to rename, at least for my use-cases. Thanks for the roadmap update, that's helpful!

As for why I need it, I have been doing some re-organization of a large local folder structure, including a rename of a folder that measures ~70G and contains many files. I'd _really_ rather not upload that entire directory over my home connection, as it would take days, so a server-side "rename" (copy + delete is fine) would be warmly welcome.

**Comment by jonhoo** [comment] 2019-06-17 13:23
Though might I suggest opening this issue up again, and only close when the feature actually lands?

**Comment by ppolewicz** [comment] 2019-06-17 13:45
The problem with copy+delete is with a client-side crash or network issue happening after copy completes but before delete is executed. Then you end up with two files.

Anothe problem is with space utilization. If your bucket has a capacity limit, you'd expect to be able to move a file when less than the size of that file is free, but with copy+delete that's not possible.

There is not much we can do with the second problem. It's just how things are in object-storage.

For the first issue, however, I might have an idea, especially now that you said you need to move a massive amount of files, not just one file.

Please provide as much information as possible about your use case. Without it, it is practically impossible to come up with a good solution.

**Comment by jonhoo** [comment] 2019-06-17 14:13
I was under the impression that b2 user server-side deduplication, so presumably the copy should take up nearly zero space?

I'm also not too concerned in my case with a crash after copy but before delete, since this is a one-off manual operation, so I can always re-issue the delete. Also, presumably both of these operations are quite fast? Though I guess copying a directory may take longer than copying a file.

Not sure what other info you are after. I have a bucket that contains a folder `foo` that I want to rename to `bar`. It contains about 70G worth of raw image files in a folder hierarchy based on dates.

**Comment by bwbeach** [comment] 2019-06-17 14:41
I agree with @ppolewicz that atomicity of "move" is hard to guarantee when it's implemented as a copy-then-delete.  (And looking forward to hearing your ideas on it.)

And, @jonhoo, B2 does *not* do any de-duplication on the server side.  The copy operation actually copies the file.  And B2 does not actually have directories.  It has files with `/` in the name, and the convention that those are treated as directories.  Renaming a "directory" means renaming all of the files with that prefix in their names.

**Comment by jonhoo** [comment] 2019-06-17 14:49
Ah, interesting, so [this](https://help.backblaze.com/hc/en-us/articles/217666638-What-Happens-If-I-Move-or-Rename-a-File-) only applies to the "personal backup" product then, and not to B2?

**Comment by bwbeach** [comment] 2019-06-17 15:59
Right.  And that's on the client side before the files are encrypted and uploaded.

**Comment by ppolewicz** [comment] 2019-06-20 02:32
@bwbeach we could make it possible to continue an interrupted operation using a bucket-info-based transaction and a file with intent list (copy that there, copy that somewhere else, delete that). Not sure if that's worth the effort, probably not.

There are some things that fall out of this design though, files could be tagged in file-info as a part of an operation and if user needs to be sure if the bucket is in consistent state, then it should be possible to check the bucket info to see the last operation number and status (assuming we only support one in progress at a time per bucket). In such case the consistency of read must be ensured by the reading client, but then backup use cases don't really have that much reading so if it's very rare and costs one call per restore, it's not really a problem.

Obviously not every client will be capable of a consistent restore, but at least some clients will, maybe b2 integration checklist will adopt a convention here and there.

**Comment by bollerdominik** [comment] 2019-09-25 20:43
Kindly asking if a rename (i.e server-side copy + delete) is still being worked on. I could really use it for my use case

**Comment by ppolewicz** [comment] 2019-09-25 21:54
I don't think anyone worked on it, but you can just call copy-file and delete in two lines of bash/powershell

**Closed** 2023-11-12 15:54 UTC
