### ISSUE TITLE
can't upload large (approx 32GB) files

### ISSUE THREAD

**Issue by mhellwig** [Backblaze/B2_Command_Line_Tool#366] opened 2017-08-28 12:42 UTC
I've been trying out backblaze-b2 as a .. fourth level backup strategy for me (fulfilling the "on another continent" condition). My problem is: The set of files I have to backup are 32GB sized. (They're basically encrypted containers, but the content I presume is irrelevant).  Now I already have the problem that the files reside on another machine than the computer that is running b2, and apparently b2 is trying to read the whole file before starting to upload it. I tried to prevent this by giving it the sha1sum, but it still takes a very long time before bits start flowing towards backblaze. But that would be an annoyance, not a problem.

The problem is that on four tries, I have not managed to upload a single file. It always ends in a broken pipe after five hours or so. And as far as I can tell b2 upload does not offer some kind of "continue" or "reput" or whatever feature that would start off where the error occured. Instead, it starts a "new version" of the same file, again running into a broken pipe after a few hours (and a few gigabytes).

What am I doing wrong?

**Comment by svonohr** [comment] 2017-08-28 16:52
Until recently the b2 API required that the hash of each uploaded part (large files are uploaded as 100MB parts) is sent before the content of this part. This requires reading each part twice and with the default setting of 10 threads the b2 cli will read about 1GB of data before actually uploading anything. Fortunately the API was extended to allow sending hashes at the end. I already implemented this in b2 CLI, so that each part is only read once, but this change has not made it to a release version yet.

Your broken pipe problems sound like a bad connection. The b2 CLI does include a resume functionality but it can only resume individual parts, not half uploaded parts. Again with 10 threads this means that you possibly need to reupload 1GB of data. You could try reducing the number of threads which may also help with slower connections.

You mentioned that a few gigabytes were already uploaded successfully. In this case there should be some parts that have finished and your upload should resume. Are you sure that files didn't change between uploads? B2 CLI uses the modified time to detect new files. Also note that resuming uploads requires comparing the local file with the hashes of the uploaded parts. This may also result in b2 CLI reading almost the entire file.

**Comment by bwbeach** [comment] 2018-07-20 19:54
Sounds like this was a connection problem, not a bug.  Closing.

**Closed by bwbeach** 2018-07-20 19:54 UTC
