### ISSUE TITLE
Host the sphinx doc somewhere, like on github pages

### ISSUE THREAD

**Issue by shuhaowu** [Backblaze/B2_Command_Line_Tool#418] opened 2018-03-03 06:02 UTC
It would be nice to be able to have the sphinx doc on github pages or something instead of having to build it manually. This would be good for those trying to use b2 as a library.

**Comment by shuhaowu** [comment] 2018-03-03 06:10
Actually does this project even provide a documented API at all? It doesn't seem like many have tried to use it like this.

**Comment by bwbeach** [comment] 2018-03-03 14:50
We don't have a documented API yet.  I think the structure is close to what's needed, but we haven't had time to do the documentation.

**Comment by ppolewicz** [comment] 2018-03-03 22:15
The API was designed so that it can be used as a backend for a filesystem and [b2 fuse](https://github.com/sondree/b2_fuse) is built on top of it.


I'm closing this as a duplicate of https://github.com/Backblaze/B2_Command_Line_Tool/issues/147

**Closed by ppolewicz** 2018-03-03 22:15 UTC
Labels: duplicate
