### ISSUE TITLE
b2 sync is dowloading the same files over and over

### ISSUE THREAD

**Issue by avimar** [Backblaze/B2_Command_Line_Tool#617] opened 2020-05-04 13:40 UTC
I ran b2 sync on a new machine to download an entire bucket. (I actually put it in the wrong folder, so I moved it, then ran b2 sync again... maybe what triggers this bug?)
But then I ran it again just to be sure... and about 2.5g/11gb needed to be downloaded again. And again.

This is on 2x machines.
```
# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.11 (stretch)
Release:        9.11
Codename:       stretch

# uname -a (two different machines on linode in different EU datacenters)
Linux sip5 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
Linux sip7 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u3 (2018-08-19) x86_64 GNU/Linux

Downloaded via PIP just today:
# b2 version
b2 command line tool, version 1.4.2
```

I found the flag `compareThreshold` so I tried the docs which said 

https://github.com/Backblaze/B2_Command_Line_Tool/blob/master/b2/console_tool.py#L1239-L1244
```
Fuzzy comparison of files based on modTime or size can be enabled by
specifying the --compareThreshold option.  This will treat modTimes
(in milliseconds) or sizes (in bytes) as the same if they are within
the comparison threshold.  Files that match, within the threshold, will
not be synced. Specifying --verbose and --dryRun can be useful to
determine comparison value differences.
```

When I tried that, I got this:
`DEBUG:b2sdk.sync.policy:File 2471/class2/1.mp3: source time 1471314905329, dest time 1471314905328, diff 1, threshold 0, diff > threshold True`

So when I run with `--compareThreshold 1` as expected, it's fine.

But that timing difference of 1ms should have been properly fixed on any one of the syncs.

----
I tried deleting one of the folders, so b2 can get a fresh start at it.
After running on the 2.5gb, it still keeps trying to download 1.5gb of it again, over and over.

`DEBUG:b2sdk.sync.policy:File refresher/2.mp3: source time 1478529308376, dest time 1478529308375, diff 1, threshold 0, diff > threshold True`

Here's the start of the --verbose, I think it's not sensitive information:

```
INFO:b2.console_tool:// ========================================  1.4.2   ======================================== \\
DEBUG:b2.console_tool:platform is Linux-4.9.0-8-amd64-x86_64-with-debian-9.11
DEBUG:b2.console_tool:Python version is CPython 2.7.13 (default, Sep 26 2018, 18:42:22)  [GCC 6.3.0 20170516]
DEBUG:b2.console_tool:locale is ('en_US', 'UTF-8')
DEBUG:b2.console_tool:filesystem encoding is UTF-8
INFO:b2.console_tool:starting command [b2.console_tool.Sync] with arguments: [u'/usr/local/bin/b2', u'sync', u'--verbose', u'--dryRun', u'b2://hotlines/2471', u'/usr/share/freeswitch/sounds/hotlines/2471']
DEBUG:b2sdk.api:calling set_thread_pool_size(self=<b2sdk.api.B2Api object at 0x7f015b940a10>, max_workers=10)
DEBUG:b2sdk.api:calling check_bucket_restrictions(self=<b2sdk.api.B2Api object at 0x7f015b940a10>, bucket_name=u'hotlines')
DEBUG:b2sdk.sync.sync:calling sync_folders(source_folder=<b2sdk.sync.folder.B2Folder object at 0x7f015b956590>, dest_folder=LocalFolder(/usr/share/freeswitch/sounds/hotlines/2471), args=Arguments({'allowEmptySource': False, 'compareThreshold': None, 'compareVersions': None, 'debugLogs': False, 'delete': False, 'destination': u'/usr/share/freeswitch/sounds/hotlines/2471', 'dryRun': True, 'excludeAllSymlinks': False, 'excludeDirRegex': [], 'excludeRegex': [], 'includeRegex': [], 'keepDays': None, 'logConfig': None, 'noProgress': False, 'replaceNewer': False, 'skipNewer': False, 'source': u'b2://hotlines/2471', 'threads': None, 'verbose': True}), now_millis=1588599500448, stdout=<open file '<stdout>', mode 'w' at 0x7f015eb51150>, no_progress=False, max_workers=10, policies_manager=<b2sdk.sync.scan_policies.ScanPoliciesManager object at 0x7f015b956410>, dry_run=True, allow_empty_source=False)
DEBUG:b2sdk.bucket:calling ls(self=Bucket<4a9c023944e48ee459970517,hotlines,None>, folder_to_list=u'2471', show_versions=True, recursive=True, fetch_count=1000)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api001.backblazeb2.com:443
DEBUG:urllib3.connectionpool:https://api001.backblazeb2.com:443 "POST /b2api/v2/b2_list_file_versions HTTP/1.1" 200 22204
```

**Comment by ppolewicz** [comment] 2020-05-04 15:39
This is very interesting indeed!

It kind of looks as if we are asking the operating system to alter the modTime of a local file but the operating system is loosing precision on the way and writing down a different modTime than we asked it to.

@avimar If I'd prepare a version of b2sdk with more detailed logs, could you run a sync (of just one small file that keeps redownloading) twice in a row on it while using that version of b2sdk with enhanced logs?

**Comment by avimar** [comment] 2020-05-04 15:45
@ppolewicz sure, let's track it down!

**Comment by mlech-reef** [comment] 2020-05-06 09:25
Hi @avimar,

We have been preparing a version with more logs, as mentioned by @ppolewicz, but during the troubleshooting, I believe we found the root cause of your problem. We think that the problem is in conversion between decimal and float numbers as B2 stores mtime as a decimal and POSIX as a float number.

You can see it in below snippet that mimics the behavior of b2 CLI tool.

```python
# test.py

import os
import random
import sys
file = sys.argv[1]
while True:
    r = random.randint(946728000000, 1577880000000)
    print(r)
    mod_time = r / 1000.0
    os.utime(file, (mod_time, mod_time))
    real_mod_time = os.path.getmtime(file)
    q = int(real_mod_time * 1000)
    try:
        assert mod_time == real_mod_time
        assert r == q
    except:
        print(mod_time, real_mod_time)
        print(r, q)
        raise
```

```
$ python test.py text.txt
...
1079789258.097 1079789258.097
1079789258097 1079789258096
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    assert r == q
AssertionError
```

The fix is quite easy, and we are going to deliver it to the `b2sdk` asap, but if you would like to test it on your own before it's officially released, I can provide you a bundled version of `b2` with that fix.

BR/ Maciek

**Comment by avimar** [comment] 2020-05-06 09:31
Great! I can wait, if you don't need a test.

It looks like you store an sha1 hash on b2's side. Perhaps you can fix the file dates without downloading the entire file again?  Probably overkill, it's only a few gb for me.

**Comment by mlech-reef** [comment] 2020-05-06 14:35
We can test on our own. I have prepared a bucket with a single file that cause the same result.

As I mentioned the solution is pretty straightforward, but there is one problem. With this fix some of the files will be calculated as 1 millisecond newer on local destination during download, if were uploaded with version that has this bug, thus `b2` would fail without `--skipNewer` or `--replaceNewer`. We need to think about the backward-compatible solution.

**Comment by avimar** [comment] 2020-05-06 15:36
So maybe what I was mentioning will help: like rsync, if the file size and name is the same, then I think it checks the file hash, and if that's the same, it just updates the time.

I'm afraid of being flippant, but if the timing is 1ms off, then you should be able to assume it's from this bug and update just the time. #whatcouldgowrong

Another idea: are you able to replicate the previous behavior of Unix, and cast to a float the way Unix was?

**Comment by mlech-reef** [comment] 2020-05-12 16:40
Using sha1 makes perfect sense, but it's another feature and another type for `--compareVersions`. For now, the default is _modification time_, so I would avoid mixing it for now.
I believe we were able to fix it in a backward-compatible way. The solution is under review right now.

ps. the problem was not in a way Unix handles casting, but in floating-point arithmetic in general. The core of the problem is described here - https://docs.python.org/3.8/tutorial/floatingpoint.html

**Comment by ppolewicz** [comment] 2020-06-17 02:25
fixed in https://github.com/Backblaze/b2-sdk-python/pull/132

**Closed by ppolewicz** 2020-06-17 02:25 UTC
Labels: bug
