### ISSUE TITLE
AFAICT no simple way to detect if a filename exists in a bucket or not

### ISSUE THREAD

**Issue by sneak** [Backblaze/B2_Command_Line_Tool#653] opened 2020-08-08 14:38 UTC
A simple `b2 file-exists` or `b2 file-info` command would be very useful for my use case, where I'm trying to script an upload-if-not-on-b2 on a per-file basis.  Parsing json output or grepping `ls` output is suboptimal for what I'm trying to do.

`b2 sync` does not allow me to specify a non-directory.  Ideally I could `b2 sync` a single file, and it'd compare the local sha1 to the server sha1, and re-upload if they don't match, or if it's missing on the server.  I was surprised I can't `b2 sync` a single file.

**Comment by ppolewicz** [comment] 2020-08-09 12:03
Hi @sneak 

Do you really need to upload exactly one file if a file with this name is not on the bucket already? Are there no more operations (multiple files in sequence, checking file metadata) in your process?

I understand what you said so far, but this seems to be a very rare use case and I would like to properly understand it to support it all the way, not by providing a command that is expensive to run (sync is amortizing the cost of listing the directory quite aggressively). Could you please describe the rest of your use case?

**Comment by sneak** [comment] 2020-08-09 14:00
Series of directories containing video. Each represents a calendar month, and they can be as large as 100-200GB. I iterate over each, make an archive, encrypt it, and then need to upload it if it doesn’t exist.

There is no command that can simply give me a pass/fail on “does a file with this file name exist in the bucket?” For that I would have to parse the listing, which means that this should no longer be a bash script.  I suppose I could try to convert it to an authed fetch url and run a HEAD on it and check for 404, but it would be nice if the b2 tool could do that for me.

**Comment by sneak** [comment] 2020-08-09 14:03
In any event, I am surprised that `b2 sync` does not work on single files, given that the sha1 hash is available from the server. “upload this file if it doesn’t match or isn’t present” seems like a pretty obvious use case.

**Comment by ppolewicz** [comment] 2020-08-09 14:44
Ok, I now understand it a little bit better. The thing about b2 is that it is a cost effective storage and it is designed as such, all the way. Looking up a single file costs the same amount of resources as looking up a thousand files, that's why we support bulk operations.

The problem here, I think, may be that you need to use an external archiver and encryption tool. Sync should do it all for you.

What tools do you use? When downloading you can't get just one file but the entire archive. Why do you archive those files?

**Comment by sneak** [comment] 2020-08-10 12:51
These are an offsite backup.  The tool I'm using is the following:

```
#!/bin/bash

set -euxo pipefail

b2 authorize-account

BUCKETNAME="com-example-fs-video"

PREFIX="com.example.fs.video"

GPGCMD="gpg
    --trust-model always
    --compress-algo none
    -r REDACTED
    -r REDACTED
    -r REDACTED
    -r REDACTED
    -r REDACTED
    -r REDACTED
    --encrypt
"

du -sh .

rm -f backup/SHASUMS
for YM in 2???/* ; do
    YMT="$(echo "$YM" | awk -F'/' '{print $2}')"
    FN="$PREFIX.$YMT.tar.gpg"
    if [[ ! -e backup/$FN ]]; then
        SIZE="$(du -cm ./$YM | tail -1  | awk -F' ' '{print $1}')"
        tar -c $YM | pv --eta -r --size ${SIZE}M | $GPGCMD > .tmp.$FN
        mv .tmp.$FN backup/$FN
        cd backup
        shasum $FN | tee $FN.shasum
        b2 upload-file --threads 10 $BUCKETNAME ./$FN.shasum $FN.shasum
        b2 upload-file --threads 10 $BUCKETNAME ./$FN $FN
        cd ..
    fi
    cd backup
    cat $FN.shasum >> SHASUMS
    cd ..
done

cd backup
b2 upload-file $BUCKETNAME ./SHASUMS SHASUMS
```

I would like to skip upload if the file already exists on the server.  I suppose you're going to suggest I go use something clunky like duplicity?

**Comment by ppolewicz** [comment] 2020-08-10 13:55
You can provide sha sum to `upload-file`, then it will be stored in metadata.

Why do you `tar` the directories?

**Comment by sneak** [comment] 2020-08-10 14:05
I'm aware that the sha1 checksum can be provided to upload-file.  The problem is that there's no single command, given the same filename, to *fetch* that sha1sum back down, without doing an `ls` and iterating through the json objects to find it.  It seems like I just need to port this tool to Python or Go and bite that bullet.

As for tar, they're being passed to GnuPG, which only encrypts a single file at a time.

**Comment by ppolewicz** [comment] 2020-08-10 20:35
Ok, but why would you need to get the checksum? If it is to check things up on upload and download, the cli should do the check for you.

It may be that you need custom logic here and writing this in python may be better (please see [b2sdk](https://github.com/Backblaze/b2-sdk-python/), it handles tokens, bucket ids, 429, retries etc), but I think the tool lacks encryption and automatic checksum verification that is equal or stronger than your standard is.

I have one more question. Do you keep a local copy of the encrypted backup package after it is uploaded to b2, or do you remove it?

An optimization to your script may be to run `b2 ls` with `jq` to get the files and checksums efficiently and then skip over the files that are already in the cloud in the `for` loop.

**Comment by mjurbanski-reef** [comment] 2023-11-10 13:58
Duplicate of #440  . Please follow it to be notified when `file-info` by name gets introduced; which will happen.

**Closed by mjurbanski-reef** 2023-11-10 13:58 UTC
Labels: enhancement, question
