### ISSUE TITLE
Possible datarace in sync/account info

### ISSUE THREAD

**Issue by svonohr** [Backblaze/B2_Command_Line_Tool#162] opened 2016-05-22 19:34 UTC
Using the b2 sync command I got this error:
`b2_upload(...): UnknownError('400 bad_request more than one upload using auth token xxxx_001_upld',) unknown error: 400 bad_request more than one upload using auth token xxxx_001_upld`

I can't reproduce this error, so it only seems to happen rarely. I think this is the second time I had this error.

**Comment by ppolewicz** [comment] 2016-09-17 22:34
@svonohr did it reproduce since May?

**Comment by svonohr** [comment] 2016-09-17 22:52
No, but I haven't been playing arround with the b2 cli in a while. Didn't we move the caching of auth tokens to RAM instead of the sqlite DB? If we did, then this bug is probably resolved.

**Comment by ppolewicz** [comment] 2016-09-17 22:57
It is in RAM only and protected by a threading lock. Closing.

**Closed by ppolewicz** 2016-09-17 22:57 UTC
Labels: bug
