### ISSUE TITLE
Error when uploading a "large file" with a restricted app key

### ISSUE THREAD

**Issue by jacquev6** [Backblaze/B2_Command_Line_Tool#608] opened 2020-03-11 18:25 UTC
Summary
=======

Using `b2` version 1.4.2 and `b2sdk` version 0.1.8.

When using an app key restricted to a bucket and a path, uploading a large file fails with an unexpected authorization error.

Using the same key to upload a small file works as expected.

Bypassing the `b2` command line and the b2sdk library, targeting the HTTP API directly using `python-requests`, it works as well.

The issue seems to be located be on the client side, either in this package or in the b2sdk library.

Also note that the same issue appears when using `b2 sync` with a restricted app key and there is a large file in the directory.

Reproduction details
==========

The gist https://gist.github.com/jacquev6/eea52abb435fd0245a301f36be511a42 provides a shell script demonstrating the issue, and a python script showing that the server-side works.

Thank you and good luck.

**Comment by ppolewicz** [comment] 2020-03-13 16:08
this is a duplicate of #591, can you use a version with that fix?

**Comment by jacquev6** [comment] 2020-03-13 16:47
Latest version of [b2 on PyPI](https://pypi.org/project/b2/) is 1.4.2, and it [requires](https://github.com/Backblaze/B2_Command_Line_Tool/blob/v1.4.2/requirements.txt) b2sdk>=0.1.8<0.2.0.

Fix for #591 is in https://github.com/Backblaze/b2-sdk-python/commit/4a8f1223347cb37ba9db3f5d642ae6c8e2bc0dd2 (comited on 2019-10-13), which is after b2sdk 1.0.2 (published on 2019-10-15).

So, I installed development versions from GitHub, (`pip install git+https://github.com/Backblaze/b2-sdk-python` then `pip install git+https://github.com/Backblaze/B2_Command_Line_Tool`) and I still get the same error:

    $ pip list | grep b2
    b2              1.4.3
    b2sdk           1.0.3

    $ b2 upload-file jacquev6 /tmp/small path/to/small-2
    URL by file name: https://f002.backblazeb2.com/file/jacquev6/path/to/small-2
    URL by fileId: https://f002.backblazeb2.com/b2api/v2/b2_download_file_by_id?fileId=4_zfd8772b489689a7b69bd0211_f104a14df386e26c4_d20200313_m163951_c002_v0001135_t0009
    {
      "action": "upload",
      "fileId": "4_zfd8772b489689a7b69bd0211_f104a14df386e26c4_d20200313_m163951_c002_v0001135_t0009",
      "fileName": "path/to/small-2",
      "size": 1048576,
      "uploadTimestamp": 1584117591000
    }

    $ b2 upload-file jacquev6 /tmp/large path/to/large-2
    ERROR: unauthorized for application key with capabilities 'listBuckets,listFiles,readFiles,shareFiles,writeFiles,deleteFiles', restricted to bucket 'jacquev6', restricted to files that start with 'path/to' (unauthorized)

What am I missing?

**Comment by ppolewicz** [comment] 2020-03-14 12:39
That's interesting. Could you please run the large upload attempt with `--verbose`?

**Comment by jacquev6** [comment] 2020-03-14 12:58
INFO:b2.console_tool:// ========================================  1.4.3   ======================================== \\
    DEBUG:b2.console_tool:platform is Darwin-18.7.0-x86_64-i386-64bit
    DEBUG:b2.console_tool:Python version is CPython 3.7.6 (default, Dec 30 2019, 19:38:28)  [Clang 11.0.0 (clang-1100.0.33.16)]
    DEBUG:b2.console_tool:locale is (None, 'UTF-8')
    DEBUG:b2.console_tool:filesystem encoding is utf-8
    INFO:b2.console_tool:starting command [b2.console_tool.UploadFile] with arguments: ['/[redacted]/b2-bug-report/venv/bin/b2', 'upload-file', '--verbose', 'jacquev6', '/tmp/large', 'path/to/large-2']
    DEBUG:b2sdk.api:calling B2Api.set_thread_pool_size(self=<b2sdk.v0.api.B2Api object at 0x106e27b50>, max_workers=10)
    DEBUG:b2sdk.api:calling B2Api.check_bucket_restrictions(self=<b2sdk.v0.api.B2Api object at 0x106e27b50>, bucket_name='jacquev6')
    DEBUG:b2sdk.api:calling B2Api.list_buckets(self=<b2sdk.v0.api.B2Api object at 0x106e27b50>, bucket_name='jacquev6')
    DEBUG:b2sdk.api:calling B2Api.check_bucket_restrictions(self=<b2sdk.v0.api.B2Api object at 0x106e27b50>, bucket_name='jacquev6')
    DEBUG:b2sdk.api:calling B2Api.check_bucket_restrictions(self=<b2sdk.v0.api.B2Api object at 0x106e27b50>, bucket_name='jacquev6')
    DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api002.backblazeb2.com:443
    DEBUG:urllib3.connectionpool:https://api002.backblazeb2.com:443 "POST /b2api/v2/b2_list_buckets HTTP/1.1" 200 298
    DEBUG:b2sdk.bucket:calling Bucket.upload_local_file(self=Bucket<fd8772b489689a7b69bd0211,jacquev6,allPrivate>, local_file='/tmp/large', file_name='path/to/large-2', content_type=None, file_infos={'src_last_modified_millis': '1583944893586'}, sha1_sum=None, min_part_size=None, progress_listener=<b2sdk.progress.TqdmProgressListener object at 0x106e3fe10>)
    DEBUG:b2sdk.bucket:calling Bucket.upload(self=Bucket<fd8772b489689a7b69bd0211,jacquev6,allPrivate>, upload_source=<b2sdk.upload_source.UploadSourceLocalFile object at 0x106e3fcd0>, file_name='path/to/large-2', content_type=None, file_info={'src_last_modified_millis': '1583944893586'}, min_part_size=None, progress_listener=<b2sdk.progress.TqdmProgressListener object at 0x106e3fe10>)
    /tmp/large:   0%|          | 0.00/215M [00:00<?, ?B/s]DEBUG:b2sdk.bucket:calling Bucket.list_unfinished_large_files(self=Bucket<fd8772b489689a7b69bd0211,jacquev6,allPrivate>, start_file_id=None, batch_size=None, prefix=None)
    DEBUG:urllib3.connectionpool:https://api002.backblazeb2.com:443 "POST /b2api/v2/b2_list_unfinished_large_files HTTP/1.1" 401 62
    ERROR:b2.console_tool:ConsoleTool command error
    Traceback (most recent call last):
      File "/[redacted]/b2-bug-report/venv/lib/python3.7/site-packages/b2sdk/session.py", line 385, in _reauthorization_loop
        return callback()
      File "/[redacted]/b2-bug-report/venv/lib/python3.7/site-packages/b2sdk/session.py", line 375, in _api_token_callback
        return raw_api_method(api_url, account_auth_token, *args, **kwargs)
      File "/[redacted]/b2-bug-report/venv/lib/python3.7/site-packages/b2sdk/raw_api.py", line 529, in list_unfinished_large_files
        namePrefix=prefix,
      File "/[redacted]/b2-bug-report/venv/lib/python3.7/site-packages/b2sdk/raw_api.py", line 301, in _post_json
        return self.b2_http.post_json_return_json(url, headers, params)
      File "/[redacted]/b2-bug-report/venv/lib/python3.7/site-packages/b2sdk/b2http.py", line 338, in post_json_return_json
        return self.post_content_return_json(url, headers, data, try_count, params)
      File "/[redacted]/b2-bug-report/venv/lib/python3.7/site-packages/b2sdk/b2http.py", line 308, in post_content_return_json
        response = _translate_and_retry(do_post, try_count, post_params)
      File "/[redacted]/b2-bug-report/venv/lib/python3.7/site-packages/b2sdk/b2http.py", line 122, in _translate_and_retry
        return _translate_errors(fcn, post_params)
      File "/[redacted]/b2-bug-report/venv/lib/python3.7/site-packages/b2sdk/b2http.py", line 63, in _translate_errors
        post_params,
    b2sdk.exception.Unauthorized:  (unauthorized)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/[redacted]/b2-bug-report/venv/lib/python3.7/site-packages/b2/console_tool.py", line 1483, in run_command
        return command.run(args)
      File "/[redacted]/b2-bug-report/venv/lib/python3.7/site-packages/b2/console_tool.py", line 1408, in run
        progress_listener=make_progress_listener(args.localFilePath, args.noProgress),
      File "/[redacted]/b2-bug-report/venv/lib/python3.7/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
        return function(*wrapee_args, **wrapee_kwargs)
      File "/[redacted]/b2-bug-report/venv/lib/python3.7/site-packages/b2sdk/bucket.py", line 468, in upload_local_file
        progress_listener=progress_listener,
      File "/[redacted]/b2-bug-report/venv/lib/python3.7/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
        return function(*wrapee_args, **wrapee_kwargs)
      File "/[redacted]/b2-bug-report/venv/lib/python3.7/site-packages/b2sdk/bucket.py", line 518, in upload
        upload_source, file_name, content_type, file_info, progress_listener
      File "/[redacted]/b2-bug-report/venv/lib/python3.7/site-packages/b2sdk/bucket.py", line 567, in _upload_large_file
        part_ranges,
      File "/[redacted]/b2-bug-report/venv/lib/python3.7/site-packages/b2sdk/bucket.py", line 608, in _find_unfinished_file_if_possible
        for file_ in self.list_unfinished_large_files():
      File "/[redacted]/b2-bug-report/venv/lib/python3.7/site-packages/b2sdk/bucket.py", line 389, in list_unfinished_large_files
        self.id_, start_file_id, batch_size, prefix
      File "/[redacted]/b2-bug-report/venv/lib/python3.7/site-packages/b2sdk/session.py", line 263, in list_unfinished_large_files
        prefix=prefix,
      File "/[redacted]/b2-bug-report/venv/lib/python3.7/site-packages/b2sdk/session.py", line 364, in _wrap_default_token
        return self._wrap_token(raw_api_method, TokenType.API, *args, **kwargs)
      File "/[redacted]/b2-bug-report/venv/lib/python3.7/site-packages/b2sdk/session.py", line 370, in _wrap_token
        return self._reauthorization_loop(partial_callback)
      File "/[redacted]/b2-bug-report/venv/lib/python3.7/site-packages/b2sdk/session.py", line 394, in _reauthorization_loop
        raise self._add_app_key_info_to_unauthorized(e)
    b2sdk.exception.Unauthorized: unauthorized for application key with capabilities 'listBuckets,listFiles,readFiles,shareFiles,writeFiles,deleteFiles', restricted to bucket 'jacquev6', restricted to files that start with 'path/to' (unauthorized)
    ERROR: unauthorized for application key with capabilities 'listBuckets,listFiles,readFiles,shareFiles,writeFiles,deleteFiles', restricted to bucket 'jacquev6', restricted to files that start with 'path/to' (unauthorized)
    /tmp/large:   0%|          | 0.00/215M [00:00<?, ?B/s]
    INFO:b2.console_tool:\\ ========================================  exit=1  ======================================== //

**Comment by ppolewicz** [comment] 2020-03-14 14:08
Thanks @jacquev6 for helping me debug this.

It turns out there is a bug here: https://github.com/Backblaze/b2-sdk-python/blob/1707190972a5d6807c7d928dd5d295dce6920915/b2sdk/bucket.py#L608

**Comment by jacquev6** [comment] 2020-03-14 14:25
Glad I could help! Let me know if you want me to test your fix.

**Closed** 2020-04-27 22:11 UTC
Labels: duplicate
